export type TenantProfileRow = {
  id: string;
  display_id?: string | number | null;
  name: string;
  trade_name: string | null;
  slug: string;
  cnpj: string | null;
  state_registration: string | null;
  municipal_registration: string | null;
  tax_regime: string | null;
  main_cnae: string | null;
  secondary_cnaes: string | null;
  opened_at: string | null;
  legal_representative: string | null;
  phone: string | null;
  whatsapp: string | null;
  email: string | null;
  financial_email: string | null;
  fiscal_email: string | null;
  website: string | null;
  logo_url: string | null;
  zip_code: string | null;
  ibge_code: string | null;
  address_line: string | null;
  address_number: string | null;
  address_complement: string | null;
  district: string | null;
  city: string | null;
  state: string | null;
  plan: string;
  status: 'active' | 'inactive' | 'suspended';
  created_at: string;
  updated_at: string;
  created_by_name: string | null;
  updated_by_name: string | null;
};

export type PlatformTenantRow = {
  id: string;
  display_id?: string | number | null;
  name: string;
  trade_name: string | null;
  slug: string;
  cnpj: string | null;
  city: string | null;
  state: string | null;
  phone: string | null;
  legal_representative: string | null;
  plan: string;
  status: 'active' | 'inactive' | 'suspended';
  created_at: string;
  updated_at: string;
  created_by_name: string | null;
  updated_by_name: string | null;
  owner_name: string | null;
  owner_email: string | null;
  owner_linked: boolean;
};

export type UpdateTenantProfileInput = {
  normalizedName: string;
  normalizedTradeName: string | null;
  normalizedSlug: string;
  normalizedCnpj: string;
  normalizedPhone: string;
  normalizedWhatsapp: string;
  normalizedPrimaryEmail: string | null;
  normalizedFinancialEmail: string | null;
  normalizedFiscalEmail: string | null;
  logoUrl: string | null;
  normalizedState: string | null;
  nextPlan: string | null;
  nextStatus: 'active' | 'inactive' | 'suspended' | null;
  stateRegistration: string | null;
  municipalRegistration: string | null;
  taxRegime: string | null;
  mainCnae: string | null;
  secondaryCnaes: string | null;
  openedAt: string | null;
  legalRepresentative: string | null;
  website: string | null;
  zipCode: string | null;
  ibgeCode: string | null;
  addressLine: string | null;
  addressNumber: string | null;
  addressComplement: string | null;
  district: string | null;
  city: string | null;
};

export type CreatePlatformTenantInput = {
  normalizedName: string;
  normalizedTradeName: string | null;
  normalizedSlug: string;
  normalizedCnpj: string;
  normalizedPhone: string;
  normalizedLegalRepresentative: string | null;
  normalizedCity: string | null;
  normalizedState: string | null;
  normalizedOwnerEmail: string;
  normalizedOwnerName: string;
  normalizedPassword: string;
  plan: string;
  status: 'active' | 'inactive' | 'suspended';
};
